//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using global::System.Linq;

namespace LightSwitchApplication.Implementation
{
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PerformanceTestDataService
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataService<global::LightSwitchApplication.Implementation.PerformanceTest>
    {
    
        public PerformanceTestDataService() : base()
        {
        }
    
        protected override global::Microsoft.LightSwitch.IDataService GetDataService(global::Microsoft.LightSwitch.IDataWorkspace dataWorkspace)
        {
            return ((global::LightSwitchApplication.DataWorkspace)dataWorkspace).PerformanceTest;
        }
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class PerformanceTestServiceImplementation
        : global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceImplementation<global::LightSwitchApplication.Implementation.PerformanceTest>
    {
        public PerformanceTestServiceImplementation(global::Microsoft.LightSwitch.IDataService dataService) : base(dataService)
        {
        }
    
    #region Queries
    #endregion

    #region Protected Methods
        protected override object CreateObject(global::System.Type type)
        {
            if (type == typeof(global::LightSwitchApplication.Implementation.Database))
            {
                return new global::LightSwitchApplication.Implementation.Database();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Package))
            {
                return new global::LightSwitchApplication.Implementation.Package();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Run))
            {
                return new global::LightSwitchApplication.Implementation.Run();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.RunStep))
            {
                return new global::LightSwitchApplication.Implementation.RunStep();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.Test))
            {
                return new global::LightSwitchApplication.Implementation.Test();
            }
            if (type == typeof(global::LightSwitchApplication.Implementation.TestStep))
            {
                return new global::LightSwitchApplication.Implementation.TestStep();
            }
    
            return base.CreateObject(type);
        }
    
        protected override global::LightSwitchApplication.Implementation.PerformanceTest CreateObjectContext()
        {
            string assemblyName = global::System.Reflection.Assembly.GetExecutingAssembly().GetName().Name;
            return new global::LightSwitchApplication.Implementation.PerformanceTest(this.GetEntityConnectionString(
                "PerformanceTest",
                "res://" + assemblyName + "/PerformanceTest.csdl|res://" + assemblyName + "/PerformanceTest.ssdl|res://" + assemblyName + "/PerformanceTest.msl",
                "System.Data.SqlClient",
                true));
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IEntityImplementation CreateEntityImplementation<T>()
        {
            if (typeof(T) == typeof(global::LightSwitchApplication.Database))
            {
                return new global::LightSwitchApplication.Implementation.Database();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Package))
            {
                return new global::LightSwitchApplication.Implementation.Package();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Run))
            {
                return new global::LightSwitchApplication.Implementation.Run();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.RunStep))
            {
                return new global::LightSwitchApplication.Implementation.RunStep();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.Test))
            {
                return new global::LightSwitchApplication.Implementation.Test();
            }
            if (typeof(T) == typeof(global::LightSwitchApplication.TestStep))
            {
                return new global::LightSwitchApplication.Implementation.TestStep();
            }
            return null;
        }
    
    #endregion
    
    }
    
    #region DataServiceImplementationFactory
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.IDataServiceFactory))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __DataServiceFactory :
        global::Microsoft.LightSwitch.ServerGenerated.Implementation.DataServiceFactory
    {
    
        protected override global::Microsoft.LightSwitch.IDataService CreateDataService(global::System.Type dataServiceType)
        {
            if (dataServiceType == typeof(global::LightSwitchApplication.PerformanceTestService))
            {
                return new global::LightSwitchApplication.PerformanceTestService();
            }
            return base.CreateDataService(dataServiceType);
        }
    
        protected override global::Microsoft.LightSwitch.Internal.IDataServiceImplementation CreateDataServiceImplementation<TDataService>(TDataService dataService)
        {
            if (typeof(TDataService) == typeof(global::LightSwitchApplication.PerformanceTestService))
            {
                return new global::LightSwitchApplication.Implementation.PerformanceTestServiceImplementation(dataService);
            }
            return base.CreateDataServiceImplementation(dataService);
        }
    }
    #endregion
    
    [global::System.ComponentModel.Composition.PartCreationPolicy(global::System.ComponentModel.Composition.CreationPolicy.Shared)]
    [global::System.ComponentModel.Composition.Export(typeof(global::Microsoft.LightSwitch.Internal.ITypeMappingProvider))]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class __TypeMapping
        : global::Microsoft.LightSwitch.Internal.ITypeMappingProvider
    {
        global::System.Type global::Microsoft.LightSwitch.Internal.ITypeMappingProvider.GetImplementationType(global::System.Type definitionType)
        {
            if (typeof(global::LightSwitchApplication.Database) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Database);
            }
            if (typeof(global::LightSwitchApplication.Package) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Package);
            }
            if (typeof(global::LightSwitchApplication.Run) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Run);
            }
            if (typeof(global::LightSwitchApplication.RunStep) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.RunStep);
            }
            if (typeof(global::LightSwitchApplication.Test) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.Test);
            }
            if (typeof(global::LightSwitchApplication.TestStep) == definitionType)
            {
                return typeof(global::LightSwitchApplication.Implementation.TestStep);
            }
            return null;
        }
    }
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Database :
        global::LightSwitchApplication.Database.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Database.DetailsClass.IImplementation.TestSteps
        {
            get
            {
                return this.TestSteps;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Database.DetailsClass.IImplementation.TestSteps1
        {
            get
            {
                return this.TestSteps1;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Package :
        global::LightSwitchApplication.Package.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Package.DetailsClass.IImplementation.TestSteps
        {
            get
            {
                return this.TestSteps;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Run :
        global::LightSwitchApplication.Run.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.Run.DetailsClass.IImplementation.Test
        {
            get
            {
                return this.Test;
            }
            set
            {
                this.Test = (global::LightSwitchApplication.Implementation.Test)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Test");
                }
            }
        }
        
        partial void OnTestIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Test");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class RunStep :
        global::LightSwitchApplication.RunStep.DetailsClass.IImplementation
    {
    
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.RunStep.DetailsClass.IImplementation.TestStep
        {
            get
            {
                return this.TestStep;
            }
            set
            {
                this.TestStep = (global::LightSwitchApplication.Implementation.TestStep)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("TestStep");
                }
            }
        }
        
        partial void OnTestStepIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("TestStep");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class Test :
        global::LightSwitchApplication.Test.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.Test.DetailsClass.IImplementation.Runs
        {
            get
            {
                return this.Runs;
            }
        }
        
        global::System.Collections.IEnumerable global::LightSwitchApplication.Test.DetailsClass.IImplementation.TestSteps
        {
            get
            {
                return this.TestSteps;
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public partial class TestStep :
        global::LightSwitchApplication.TestStep.DetailsClass.IImplementation
    {
    
        global::System.Collections.IEnumerable global::LightSwitchApplication.TestStep.DetailsClass.IImplementation.RunSteps
        {
            get
            {
                return this.RunSteps;
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TestStep.DetailsClass.IImplementation.SrcDatabase
        {
            get
            {
                return this.SrcDatabase;
            }
            set
            {
                this.SrcDatabase = (global::LightSwitchApplication.Implementation.Database)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("SrcDatabase");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TestStep.DetailsClass.IImplementation.Package
        {
            get
            {
                return this.Package;
            }
            set
            {
                this.Package = (global::LightSwitchApplication.Implementation.Package)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Package");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TestStep.DetailsClass.IImplementation.DestDatabase
        {
            get
            {
                return this.DestDatabase;
            }
            set
            {
                this.DestDatabase = (global::LightSwitchApplication.Implementation.Database)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("DestDatabase");
                }
            }
        }
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementation global::LightSwitchApplication.TestStep.DetailsClass.IImplementation.Test
        {
            get
            {
                return this.Test;
            }
            set
            {
                this.Test = (global::LightSwitchApplication.Implementation.Test)value;
                if (this.__host != null)
                {
                    this.__host.RaisePropertyChanged("Test");
                }
            }
        }
        
        partial void OnDestDatabaseIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("SrcDatabase");
            }
        }
        
        partial void OnPackageIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Package");
            }
        }
        
        partial void OnSrcDatabaseIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("DestDatabase");
            }
        }
        
        partial void OnTestIDChanged()
        {
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged("Test");
            }
        }
        
        #region IEntityImplementation Members
        private global::Microsoft.LightSwitch.Internal.IEntityImplementationHost __host;
        
        global::Microsoft.LightSwitch.Internal.IEntityImplementationHost global::Microsoft.LightSwitch.Internal.IEntityImplementation.Host
        {
            get
            {
                return this.__host;
            }
        }
        
        void global::Microsoft.LightSwitch.Internal.IEntityImplementation.Initialize(global::Microsoft.LightSwitch.Internal.IEntityImplementationHost host)
        {
            this.__host = host;
        }
        
        protected override void OnPropertyChanged(string propertyName)
        {
            base.OnPropertyChanged(propertyName);
            if (this.__host != null)
            {
                this.__host.RaisePropertyChanged(propertyName);
            }
        }
        #endregion
    }
    
}

