

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Database : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Database entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Database()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Database(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Database> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Database.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Database_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Database_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int DatabaseID
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string DatabaseName
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseName);
            }
            set
            {
                global::LightSwitchApplication.Database.DetailsClass.SetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void DatabaseName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ServerName
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.ServerName);
            }
            set
            {
                global::LightSwitchApplication.Database.DetailsClass.SetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.ServerName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServerName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServerName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ServerName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Database.DetailsClass.SetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Username
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Username);
            }
            set
            {
                global::LightSwitchApplication.Database.DetailsClass.SetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Username, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Username_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Password
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Password);
            }
            set
            {
                global::LightSwitchApplication.Database.DetailsClass.SetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Password, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Password_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TestStep> TestSteps
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TestStep> TestStepsQuery
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetQuery(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TestStep> TestSteps1
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetValue(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps1);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TestStep> TestSteps1Query
        {
            get
            {
                return global::LightSwitchApplication.Database.DetailsClass.GetQuery(this, global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps1);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Database,
                global::LightSwitchApplication.Database.DetailsClass,
                global::LightSwitchApplication.Database.DetailsClass.IImplementation,
                global::LightSwitchApplication.Database.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>.Entry
                __DatabaseEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>.Entry(
                    global::LightSwitchApplication.Database.DetailsClass.__Database_CreateNew,
                    global::LightSwitchApplication.Database.DetailsClass.__Database_Created,
                    global::LightSwitchApplication.Database.DetailsClass.__Database_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Database __Database_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Database> es)
            {
                return new global::LightSwitchApplication.Database(es);
            }
            private static void __Database_Created(global::LightSwitchApplication.Database e)
            {
                e.Database_Created();
            }
            private static bool __Database_AllowSaveWithErrors(global::LightSwitchApplication.Database e)
            {
                bool result = false;
                e.Database_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Database.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int> DatabaseID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string> DatabaseName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.DatabaseName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string> ServerName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.ServerName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string> Username
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Username) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string> Password
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.Password) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep> TestSteps
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep> TestSteps1
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps1) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int DatabaseID { get; }
                new string DatabaseName { get; set; }
                new string ServerName { get; set; }
                new string Description { get; set; }
                new string Username { get; set; }
                new string Password { get; set; }
                new global::System.Collections.IEnumerable TestSteps { get; }
                new global::System.Collections.IEnumerable TestSteps1 { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int>.Entry
                    DatabaseID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int>.Entry(
                        "DatabaseID",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseID_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseID_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseID_OnValueChanged);
                private static void _DatabaseID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._DatabaseID, sf);
                }
                private static bool _DatabaseID_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.DatabaseID_IsReadOnly(ref result);
                    return result;
                }
                private static void _DatabaseID_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DatabaseID_Validate(r);
                }
                private static int _DatabaseID_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.DatabaseID;
                }
                private static void _DatabaseID_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.DatabaseID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry
                    DatabaseName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry(
                        "DatabaseName",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_GetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_SetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._DatabaseName_OnValueChanged);
                private static void _DatabaseName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._DatabaseName, sf);
                }
                private static bool _DatabaseName_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.DatabaseName_IsReadOnly(ref result);
                    return result;
                }
                private static void _DatabaseName_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.DatabaseName_Validate(r);
                }
                private static string _DatabaseName_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.DatabaseName;
                }
                private static void _DatabaseName_SetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d, string v)
                {
                    d.ImplementationEntity.DatabaseName = v;
                }
                private static void _DatabaseName_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.DatabaseName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry
                    ServerName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry(
                        "ServerName",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_GetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_SetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._ServerName_OnValueChanged);
                private static void _ServerName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._ServerName, sf);
                }
                private static bool _ServerName_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.ServerName_IsReadOnly(ref result);
                    return result;
                }
                private static void _ServerName_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ServerName_Validate(r);
                }
                private static string _ServerName_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.ServerName;
                }
                private static void _ServerName_SetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ServerName = v;
                }
                private static void _ServerName_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.ServerName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry
                    Username = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry(
                        "Username",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_GetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_SetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Username_OnValueChanged);
                private static void _Username_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._Username, sf);
                }
                private static bool _Username_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.Username_IsReadOnly(ref result);
                    return result;
                }
                private static void _Username_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Username_Validate(r);
                }
                private static string _Username_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.Username;
                }
                private static void _Username_SetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Username = v;
                }
                private static void _Username_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.Username_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry
                    Password = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Entry(
                        "Password",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_ComputeIsReadOnly,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_Validate,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_GetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_SetImplementationValue,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._Password_OnValueChanged);
                private static void _Password_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._Password, sf);
                }
                private static bool _Password_ComputeIsReadOnly(global::LightSwitchApplication.Database e)
                {
                    bool result = false;
                    e.Password_IsReadOnly(ref result);
                    return result;
                }
                private static void _Password_Validate(global::LightSwitchApplication.Database e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Password_Validate(r);
                }
                private static string _Password_GetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.Password;
                }
                private static void _Password_SetImplementationValue(global::LightSwitchApplication.Database.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Password = v;
                }
                private static void _Password_OnValueChanged(global::LightSwitchApplication.Database e)
                {
                    e.Password_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Entry
                    TestSteps = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Entry(
                        "TestSteps",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps_GetReferencedEntities,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps_GetEntityCollection);
                private static void _TestSteps_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._TestSteps, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TestStep> _TestSteps_GetReferencedEntities(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TestStep, global::LightSwitchApplication.TestStep.DetailsClass>(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps, ref d._TestSteps);
                }
                private static global::System.Collections.IEnumerable _TestSteps_GetEntityCollection(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.TestSteps;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Entry
                    TestSteps1 = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Entry(
                        "TestSteps1",
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps1_Stub,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps1_GetReferencedEntities,
                        global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties._TestSteps1_GetEntityCollection);
                private static void _TestSteps1_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Database.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Data> c, global::LightSwitchApplication.Database.DetailsClass d, object sf)
                {
                    c(d, ref d._TestSteps1, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TestStep> _TestSteps1_GetReferencedEntities(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TestStep, global::LightSwitchApplication.TestStep.DetailsClass>(global::LightSwitchApplication.Database.DetailsClass.PropertySetProperties.TestSteps1, ref d._TestSteps1);
                }
                private static global::System.Collections.IEnumerable _TestSteps1_GetEntityCollection(global::LightSwitchApplication.Database.DetailsClass d)
                {
                    return d.ImplementationEntity.TestSteps1;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, int>.Data _DatabaseID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data _DatabaseName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data _ServerName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data _Username;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, string>.Data _Password;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Data _TestSteps;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Database, global::LightSwitchApplication.Database.DetailsClass, global::LightSwitchApplication.TestStep>.Data _TestSteps1;
            
        }
    
        #endregion
    }
    
    #endregion
}
