

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Test : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Test entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Test()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Test(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Test> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Test.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Test_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Test_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int TestID
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string TestName
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestName);
            }
            set
            {
                global::LightSwitchApplication.Test.DetailsClass.SetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Description
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Description);
            }
            set
            {
                global::LightSwitchApplication.Test.DetailsClass.SetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Description, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Description_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Run> Runs
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Runs);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Run> RunsQuery
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetQuery(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Runs);
            }
        }

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.TestStep> TestSteps
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetValue(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestSteps);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.TestStep> TestStepsQuery
        {
            get
            {
                return global::LightSwitchApplication.Test.DetailsClass.GetQuery(this, global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestSteps);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Test,
                global::LightSwitchApplication.Test.DetailsClass,
                global::LightSwitchApplication.Test.DetailsClass.IImplementation,
                global::LightSwitchApplication.Test.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>.Entry
                __TestEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>.Entry(
                    global::LightSwitchApplication.Test.DetailsClass.__Test_CreateNew,
                    global::LightSwitchApplication.Test.DetailsClass.__Test_Created,
                    global::LightSwitchApplication.Test.DetailsClass.__Test_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Test __Test_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Test> es)
            {
                return new global::LightSwitchApplication.Test(es);
            }
            private static void __Test_Created(global::LightSwitchApplication.Test e)
            {
                e.Test_Created();
            }
            private static bool __Test_AllowSaveWithErrors(global::LightSwitchApplication.Test e)
            {
                bool result = false;
                e.Test_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Test.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int> TestID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string> TestName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string> Description
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Description) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run> Runs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Runs) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep> TestSteps
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestSteps) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int TestID { get; }
                new string TestName { get; set; }
                new string Description { get; set; }
                new global::System.Collections.IEnumerable Runs { get; }
                new global::System.Collections.IEnumerable TestSteps { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int>.Entry
                    TestID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int>.Entry(
                        "TestID",
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestID_Stub,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestID_Validate,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestID_OnValueChanged);
                private static void _TestID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Test.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int>.Data> c, global::LightSwitchApplication.Test.DetailsClass d, object sf)
                {
                    c(d, ref d._TestID, sf);
                }
                private static bool _TestID_ComputeIsReadOnly(global::LightSwitchApplication.Test e)
                {
                    bool result = false;
                    e.TestID_IsReadOnly(ref result);
                    return result;
                }
                private static void _TestID_Validate(global::LightSwitchApplication.Test e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TestID_Validate(r);
                }
                private static int _TestID_GetImplementationValue(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.ImplementationEntity.TestID;
                }
                private static void _TestID_OnValueChanged(global::LightSwitchApplication.Test e)
                {
                    e.TestID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Entry
                    TestName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Entry(
                        "TestName",
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_Stub,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_Validate,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_GetImplementationValue,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_SetImplementationValue,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestName_OnValueChanged);
                private static void _TestName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Test.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Data> c, global::LightSwitchApplication.Test.DetailsClass d, object sf)
                {
                    c(d, ref d._TestName, sf);
                }
                private static bool _TestName_ComputeIsReadOnly(global::LightSwitchApplication.Test e)
                {
                    bool result = false;
                    e.TestName_IsReadOnly(ref result);
                    return result;
                }
                private static void _TestName_Validate(global::LightSwitchApplication.Test e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TestName_Validate(r);
                }
                private static string _TestName_GetImplementationValue(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.ImplementationEntity.TestName;
                }
                private static void _TestName_SetImplementationValue(global::LightSwitchApplication.Test.DetailsClass d, string v)
                {
                    d.ImplementationEntity.TestName = v;
                }
                private static void _TestName_OnValueChanged(global::LightSwitchApplication.Test e)
                {
                    e.TestName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Entry
                    Description = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Entry(
                        "Description",
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_Stub,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_ComputeIsReadOnly,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_Validate,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_GetImplementationValue,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_SetImplementationValue,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Description_OnValueChanged);
                private static void _Description_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Test.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Data> c, global::LightSwitchApplication.Test.DetailsClass d, object sf)
                {
                    c(d, ref d._Description, sf);
                }
                private static bool _Description_ComputeIsReadOnly(global::LightSwitchApplication.Test e)
                {
                    bool result = false;
                    e.Description_IsReadOnly(ref result);
                    return result;
                }
                private static void _Description_Validate(global::LightSwitchApplication.Test e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Description_Validate(r);
                }
                private static string _Description_GetImplementationValue(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.ImplementationEntity.Description;
                }
                private static void _Description_SetImplementationValue(global::LightSwitchApplication.Test.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Description = v;
                }
                private static void _Description_OnValueChanged(global::LightSwitchApplication.Test e)
                {
                    e.Description_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run>.Entry
                    Runs = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run>.Entry(
                        "Runs",
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Runs_Stub,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Runs_GetReferencedEntities,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._Runs_GetEntityCollection);
                private static void _Runs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Test.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run>.Data> c, global::LightSwitchApplication.Test.DetailsClass d, object sf)
                {
                    c(d, ref d._Runs, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Run> _Runs_GetReferencedEntities(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.Runs, ref d._Runs);
                }
                private static global::System.Collections.IEnumerable _Runs_GetEntityCollection(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.ImplementationEntity.Runs;
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep>.Entry
                    TestSteps = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep>.Entry(
                        "TestSteps",
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestSteps_Stub,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestSteps_GetReferencedEntities,
                        global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties._TestSteps_GetEntityCollection);
                private static void _TestSteps_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Test.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep>.Data> c, global::LightSwitchApplication.Test.DetailsClass d, object sf)
                {
                    c(d, ref d._TestSteps, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.TestStep> _TestSteps_GetReferencedEntities(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.TestStep, global::LightSwitchApplication.TestStep.DetailsClass>(global::LightSwitchApplication.Test.DetailsClass.PropertySetProperties.TestSteps, ref d._TestSteps);
                }
                private static global::System.Collections.IEnumerable _TestSteps_GetEntityCollection(global::LightSwitchApplication.Test.DetailsClass d)
                {
                    return d.ImplementationEntity.TestSteps;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, int>.Data _TestID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Data _TestName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, string>.Data _Description;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.Run>.Data _Runs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Test, global::LightSwitchApplication.Test.DetailsClass, global::LightSwitchApplication.TestStep>.Data _TestSteps;
            
        }
    
        #endregion
    }
    
    #endregion
}
