
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Aphelion_DB_BalancingData datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Aphelion_DB_BalancingDataService Aphelion_DB_BalancingData
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Aphelion_DB_BalancingData);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Aphelion_DB_BalancingData;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService> Aphelion_DB_BalancingData
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Aphelion_DB_BalancingData) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService>.Entry
                    Aphelion_DB_BalancingData = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService>.Entry(
                        "Aphelion_DB_BalancingData",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._Aphelion_DB_BalancingData_Stub);
                private static void _Aphelion_DB_BalancingData_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._Aphelion_DB_BalancingData, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingDataService>.Data _Aphelion_DB_BalancingData;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the Aphelion_DB_BalancingData datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Aphelion_DB_BalancingData : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Aphelion_DB_BalancingData() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the DataSources entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DataSource> DataSources
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.DataSources);
            }
        }
        
        /// <summary>
        /// Gets the DataSourceTypes entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.DataSourceType> DataSourceTypes
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.DataSourceTypes);
            }
        }
        
        /// <summary>
        /// Gets the FunctionalAreas entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.FunctionalArea> FunctionalAreas
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.FunctionalAreas);
            }
        }
        
        /// <summary>
        /// Gets the Queries entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Query> Queries
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Queries);
            }
        }
        
        /// <summary>
        /// Gets the Results entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Result> Results
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Results);
            }
        }
        
        /// <summary>
        /// Gets the Runs entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Run> Runs
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Runs);
            }
        }
        
        /// <summary>
        /// Gets the Tests entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Test> Tests
        {
            get
            {
                return global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.GetValue(this, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Tests);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="DataSourceID">
        /// The value of the 'DataSourceID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.DataSource DataSources_Single(global::System.Nullable<int> DataSourceID)
        {
            return this.Details.Methods.DataSources_Single.CreateInvocation(DataSourceID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="DataSourceID">
        /// The value of the 'DataSourceID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.DataSource DataSources_SingleOrDefault(global::System.Nullable<int> DataSourceID)
        {
            return this.Details.Methods.DataSources_SingleOrDefault.CreateInvocation(DataSourceID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="DataSourceTypeID">
        /// The value of the 'DataSourceTypeID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.DataSourceType DataSourceTypes_Single(global::System.Nullable<int> DataSourceTypeID)
        {
            return this.Details.Methods.DataSourceTypes_Single.CreateInvocation(DataSourceTypeID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="DataSourceTypeID">
        /// The value of the 'DataSourceTypeID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.DataSourceType DataSourceTypes_SingleOrDefault(global::System.Nullable<int> DataSourceTypeID)
        {
            return this.Details.Methods.DataSourceTypes_SingleOrDefault.CreateInvocation(DataSourceTypeID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="FunctionalAreaID">
        /// The value of the 'FunctionalAreaID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.FunctionalArea FunctionalAreas_Single(global::System.Nullable<int> FunctionalAreaID)
        {
            return this.Details.Methods.FunctionalAreas_Single.CreateInvocation(FunctionalAreaID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="FunctionalAreaID">
        /// The value of the 'FunctionalAreaID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.FunctionalArea FunctionalAreas_SingleOrDefault(global::System.Nullable<int> FunctionalAreaID)
        {
            return this.Details.Methods.FunctionalAreas_SingleOrDefault.CreateInvocation(FunctionalAreaID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="QueryID">
        /// The value of the 'QueryID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Query Queries_Single(global::System.Nullable<int> QueryID)
        {
            return this.Details.Methods.Queries_Single.CreateInvocation(QueryID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="QueryID">
        /// The value of the 'QueryID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Query Queries_SingleOrDefault(global::System.Nullable<int> QueryID)
        {
            return this.Details.Methods.Queries_SingleOrDefault.CreateInvocation(QueryID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="ResultID">
        /// The value of the 'ResultID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Result Results_Single(global::System.Nullable<int> ResultID)
        {
            return this.Details.Methods.Results_Single.CreateInvocation(ResultID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="ResultID">
        /// The value of the 'ResultID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Result Results_SingleOrDefault(global::System.Nullable<int> ResultID)
        {
            return this.Details.Methods.Results_SingleOrDefault.CreateInvocation(ResultID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="RunID">
        /// The value of the 'RunID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Run Runs_Single(global::System.Nullable<int> RunID)
        {
            return this.Details.Methods.Runs_Single.CreateInvocation(RunID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="RunID">
        /// The value of the 'RunID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Run Runs_SingleOrDefault(global::System.Nullable<int> RunID)
        {
            return this.Details.Methods.Runs_SingleOrDefault.CreateInvocation(RunID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="TestID">
        /// The value of the 'TestID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Test Tests_Single(global::System.Nullable<int> TestID)
        {
            return this.Details.Methods.Tests_Single.CreateInvocation(TestID).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="TestID">
        /// The value of the 'TestID' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Test Tests_SingleOrDefault(global::System.Nullable<int> TestID)
        {
            return this.Details.Methods.Tests_SingleOrDefault.CreateInvocation(TestID).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DataSource> DataSourcesSorted()
        {
            return this.Details.Methods.DataSourcesSorted.CreateInvocation().Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.DataSourceType> DataSourceTypesSorted()
        {
            return this.Details.Methods.DataSourceTypesSorted.CreateInvocation().Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.FunctionalArea> FunctionalAreasSorted()
        {
            return this.Details.Methods.FunctionalAreasSorted.CreateInvocation().Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Query> QueriesSorted()
        {
            return this.Details.Methods.QueriesSorted.CreateInvocation().Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        public global::Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Test> TestsSorted()
        {
            return this.Details.Methods.TestsSorted.CreateInvocation().Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySet, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSources_Single;
                var initializePropertyEntry = global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.DataSources;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource> DataSources_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSources_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource> DataSources_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSources_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType> DataSourceTypes_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSourceTypes_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType> DataSourceTypes_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSourceTypes_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea> FunctionalAreas_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.FunctionalAreas_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea> FunctionalAreas_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.FunctionalAreas_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query> Queries_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Queries_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query> Queries_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Queries_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result> Results_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Results_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result> Results_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Results_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run> Runs_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Runs_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run> Runs_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Runs_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test> Tests_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Tests_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test> Tests_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.Tests_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource> DataSourcesSorted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSourcesSorted) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType> DataSourceTypesSorted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.DataSourceTypesSorted) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea> FunctionalAreasSorted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.FunctionalAreasSorted) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query> QueriesSorted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.QueriesSorted) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test> TestsSorted
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties.TestsSorted) as global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource> DataSources
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.DataSources) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType> DataSourceTypes
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.DataSourceTypes) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea> FunctionalAreas
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.FunctionalAreas) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query> Queries
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Queries) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result> Results
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Results) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run> Runs
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Runs) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test> Tests
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties.Tests) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry
                    DataSources_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry(
                        "DataSources_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSources_Single_Stub);
                private static void _DataSources_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSources_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry
                    DataSources_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry(
                        "DataSources_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSources_SingleOrDefault_Stub);
                private static void _DataSources_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSources_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry
                    DataSourceTypes_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry(
                        "DataSourceTypes_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSourceTypes_Single_Stub);
                private static void _DataSourceTypes_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSourceTypes_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry
                    DataSourceTypes_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry(
                        "DataSourceTypes_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSourceTypes_SingleOrDefault_Stub);
                private static void _DataSourceTypes_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSourceTypes_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry
                    FunctionalAreas_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry(
                        "FunctionalAreas_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._FunctionalAreas_Single_Stub);
                private static void _FunctionalAreas_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._FunctionalAreas_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry
                    FunctionalAreas_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry(
                        "FunctionalAreas_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._FunctionalAreas_SingleOrDefault_Stub);
                private static void _FunctionalAreas_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._FunctionalAreas_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry
                    Queries_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry(
                        "Queries_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Queries_Single_Stub);
                private static void _Queries_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Queries_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry
                    Queries_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry(
                        "Queries_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Queries_SingleOrDefault_Stub);
                private static void _Queries_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Queries_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry
                    Results_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry(
                        "Results_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Results_Single_Stub);
                private static void _Results_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Results_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry
                    Results_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry(
                        "Results_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Results_SingleOrDefault_Stub);
                private static void _Results_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Results_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry
                    Runs_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry(
                        "Runs_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Runs_Single_Stub);
                private static void _Runs_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Runs_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry
                    Runs_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry(
                        "Runs_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Runs_SingleOrDefault_Stub);
                private static void _Runs_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Runs_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry
                    Tests_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry(
                        "Tests_Single",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Tests_Single_Stub);
                private static void _Tests_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tests_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry
                    Tests_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry(
                        "Tests_SingleOrDefault",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._Tests_SingleOrDefault_Stub);
                private static void _Tests_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tests_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry
                    DataSourcesSorted = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry(
                        "DataSourcesSorted",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSourcesSorted_Stub);
                private static void _DataSourcesSorted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSourcesSorted, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry
                    DataSourceTypesSorted = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry(
                        "DataSourceTypesSorted",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._DataSourceTypesSorted_Stub);
                private static void _DataSourceTypesSorted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSourceTypesSorted, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry
                    FunctionalAreasSorted = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry(
                        "FunctionalAreasSorted",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._FunctionalAreasSorted_Stub);
                private static void _FunctionalAreasSorted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._FunctionalAreasSorted, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry
                    QueriesSorted = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry(
                        "QueriesSorted",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._QueriesSorted_Stub);
                private static void _QueriesSorted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._QueriesSorted, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry
                    TestsSorted = new global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry(
                        "TestsSorted",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.MethodSetProperties._TestsSorted_Stub);
                private static void _TestsSorted_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._TestsSorted, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry
                    DataSources = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Entry(
                        "DataSources",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._DataSources_Stub);
                private static void _DataSources_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSources, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry
                    DataSourceTypes = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Entry(
                        "DataSourceTypes",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._DataSourceTypes_Stub);
                private static void _DataSourceTypes_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._DataSourceTypes, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry
                    FunctionalAreas = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Entry(
                        "FunctionalAreas",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._FunctionalAreas_Stub);
                private static void _FunctionalAreas_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._FunctionalAreas, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry
                    Queries = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Entry(
                        "Queries",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._Queries_Stub);
                private static void _Queries_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Queries, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry
                    Results = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Entry(
                        "Results",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._Results_Stub);
                private static void _Results_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Results, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry
                    Runs = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Entry(
                        "Runs",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._Runs_Stub);
                private static void _Runs_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Runs, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry
                    Tests = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Entry(
                        "Tests",
                        global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass.PropertySetProperties._Tests_Stub);
                private static void _Tests_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data> c, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass d, object sf)
                {
                    c(d, ref d._Tests, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data _DataSources;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data _DataSourceTypes;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data _FunctionalAreas;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data _Queries;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data _Results;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data _Runs;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data _Tests;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data _DataSources_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data _DataSources_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data _DataSourceTypes_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data _DataSourceTypes_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data _FunctionalAreas_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data _FunctionalAreas_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data _Queries_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data _Queries_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data _Results_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Result>.Data _Results_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data _Runs_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Run>.Data _Runs_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data _Tests_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data _Tests_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSource>.Data _DataSourcesSorted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.DataSourceType>.Data _DataSourceTypesSorted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.FunctionalArea>.Data _FunctionalAreasSorted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Query>.Data _QueriesSorted;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateQueryMethod<global::LightSwitchApplication.Aphelion_DB_BalancingData, global::LightSwitchApplication.Aphelion_DB_BalancingData.DetailsClass, global::LightSwitchApplication.Test>.Data _TestsSorted;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
