

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Run : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Run entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Run()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Run(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Run> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Run.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Run_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Run_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int RunID
        {
            get
            {
                return global::LightSwitchApplication.Run.DetailsClass.GetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string RunName
        {
            get
            {
                return global::LightSwitchApplication.Run.DetailsClass.GetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunName);
            }
            set
            {
                global::LightSwitchApplication.Run.DetailsClass.SetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunName, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunName_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunName_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunName_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime RunTime
        {
            get
            {
                return global::LightSwitchApplication.Run.DetailsClass.GetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunTime);
            }
            set
            {
                global::LightSwitchApplication.Run.DetailsClass.SetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void RunTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntityCollection<global::LightSwitchApplication.Result> Results
        {
            get
            {
                return global::LightSwitchApplication.Run.DetailsClass.GetValue(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.Results);
            }
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Microsoft.LightSwitch.IDataServiceQueryable<global::LightSwitchApplication.Result> ResultsQuery
        {
            get
            {
                return global::LightSwitchApplication.Run.DetailsClass.GetQuery(this, global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.Results);
            }
        }

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Run,
                global::LightSwitchApplication.Run.DetailsClass,
                global::LightSwitchApplication.Run.DetailsClass.IImplementation,
                global::LightSwitchApplication.Run.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>.Entry
                __RunEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>.Entry(
                    global::LightSwitchApplication.Run.DetailsClass.__Run_CreateNew,
                    global::LightSwitchApplication.Run.DetailsClass.__Run_Created,
                    global::LightSwitchApplication.Run.DetailsClass.__Run_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Run __Run_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Run> es)
            {
                return new global::LightSwitchApplication.Run(es);
            }
            private static void __Run_Created(global::LightSwitchApplication.Run e)
            {
                e.Run_Created();
            }
            private static bool __Run_AllowSaveWithErrors(global::LightSwitchApplication.Run e)
            {
                bool result = false;
                e.Run_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Run.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int> RunID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string> RunName
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunName) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime> RunTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.RunTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result> Results
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.Results) as global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int RunID { get; }
                new string RunName { get; set; }
                new global::System.DateTime RunTime { get; set; }
                new global::System.Collections.IEnumerable Results { get; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int>.Entry
                    RunID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int>.Entry(
                        "RunID",
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunID_Stub,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunID_Validate,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunID_OnValueChanged);
                private static void _RunID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Run.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int>.Data> c, global::LightSwitchApplication.Run.DetailsClass d, object sf)
                {
                    c(d, ref d._RunID, sf);
                }
                private static bool _RunID_ComputeIsReadOnly(global::LightSwitchApplication.Run e)
                {
                    bool result = false;
                    e.RunID_IsReadOnly(ref result);
                    return result;
                }
                private static void _RunID_Validate(global::LightSwitchApplication.Run e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RunID_Validate(r);
                }
                private static int _RunID_GetImplementationValue(global::LightSwitchApplication.Run.DetailsClass d)
                {
                    return d.ImplementationEntity.RunID;
                }
                private static void _RunID_OnValueChanged(global::LightSwitchApplication.Run e)
                {
                    e.RunID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string>.Entry
                    RunName = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string>.Entry(
                        "RunName",
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_Stub,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_ComputeIsReadOnly,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_Validate,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_GetImplementationValue,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_SetImplementationValue,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunName_OnValueChanged);
                private static void _RunName_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Run.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string>.Data> c, global::LightSwitchApplication.Run.DetailsClass d, object sf)
                {
                    c(d, ref d._RunName, sf);
                }
                private static bool _RunName_ComputeIsReadOnly(global::LightSwitchApplication.Run e)
                {
                    bool result = false;
                    e.RunName_IsReadOnly(ref result);
                    return result;
                }
                private static void _RunName_Validate(global::LightSwitchApplication.Run e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RunName_Validate(r);
                }
                private static string _RunName_GetImplementationValue(global::LightSwitchApplication.Run.DetailsClass d)
                {
                    return d.ImplementationEntity.RunName;
                }
                private static void _RunName_SetImplementationValue(global::LightSwitchApplication.Run.DetailsClass d, string v)
                {
                    d.ImplementationEntity.RunName = v;
                }
                private static void _RunName_OnValueChanged(global::LightSwitchApplication.Run e)
                {
                    e.RunName_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime>.Entry
                    RunTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime>.Entry(
                        "RunTime",
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_Stub,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_Validate,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_GetImplementationValue,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_SetImplementationValue,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._RunTime_OnValueChanged);
                private static void _RunTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Run.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Run.DetailsClass d, object sf)
                {
                    c(d, ref d._RunTime, sf);
                }
                private static bool _RunTime_ComputeIsReadOnly(global::LightSwitchApplication.Run e)
                {
                    bool result = false;
                    e.RunTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _RunTime_Validate(global::LightSwitchApplication.Run e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.RunTime_Validate(r);
                }
                private static global::System.DateTime _RunTime_GetImplementationValue(global::LightSwitchApplication.Run.DetailsClass d)
                {
                    return d.ImplementationEntity.RunTime;
                }
                private static void _RunTime_SetImplementationValue(global::LightSwitchApplication.Run.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.RunTime = global::LightSwitchApplication.Run.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _RunTime_OnValueChanged(global::LightSwitchApplication.Run e)
                {
                    e.RunTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result>.Entry
                    Results = new global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result>.Entry(
                        "Results",
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._Results_Stub,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._Results_GetReferencedEntities,
                        global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties._Results_GetEntityCollection);
                private static void _Results_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Run.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result>.Data> c, global::LightSwitchApplication.Run.DetailsClass d, object sf)
                {
                    c(d, ref d._Results, sf);
                }
                private static global::System.Collections.Generic.IEnumerable<global::LightSwitchApplication.Result> _Results_GetReferencedEntities(global::LightSwitchApplication.Run.DetailsClass d)
                {
                    return d.GetReferencedEntities<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>(global::LightSwitchApplication.Run.DetailsClass.PropertySetProperties.Results, ref d._Results);
                }
                private static global::System.Collections.IEnumerable _Results_GetEntityCollection(global::LightSwitchApplication.Run.DetailsClass d)
                {
                    return d.ImplementationEntity.Results;
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, int>.Data _RunID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, string>.Data _RunName;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::System.DateTime>.Data _RunTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityCollectionProperty<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass, global::LightSwitchApplication.Result>.Data _Results;
            
        }
    
        #endregion
    }
    
    #endregion
}
