

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
    public sealed partial class Result : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Result entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Result()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Result(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Result> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Result.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Result_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Result_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int ResultID
        {
            get
            {
                return global::LightSwitchApplication.Result.DetailsClass.GetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.ResultID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResultID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResultID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ResultID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<double> TestResult
        {
            get
            {
                return global::LightSwitchApplication.Result.DetailsClass.GetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestResult);
            }
            set
            {
                global::LightSwitchApplication.Result.DetailsClass.SetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestResult, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestResult_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestResult_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestResult_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime TestDateTime
        {
            get
            {
                return global::LightSwitchApplication.Result.DetailsClass.GetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestDateTime);
            }
            set
            {
                global::LightSwitchApplication.Result.DetailsClass.SetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestDateTime, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestDateTime_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestDateTime_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void TestDateTime_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Query Query
        {
            get
            {
                return global::LightSwitchApplication.Result.DetailsClass.GetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query);
            }
            set
            {
                global::LightSwitchApplication.Result.DetailsClass.SetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Query_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Run Run
        {
            get
            {
                return global::LightSwitchApplication.Result.DetailsClass.GetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run);
            }
            set
            {
                global::LightSwitchApplication.Result.DetailsClass.SetValue(this, global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Run_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Run_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Run_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Result,
                global::LightSwitchApplication.Result.DetailsClass,
                global::LightSwitchApplication.Result.DetailsClass.IImplementation,
                global::LightSwitchApplication.Result.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.ResultID;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>.Entry
                __ResultEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>.Entry(
                    global::LightSwitchApplication.Result.DetailsClass.__Result_CreateNew,
                    global::LightSwitchApplication.Result.DetailsClass.__Result_Created,
                    global::LightSwitchApplication.Result.DetailsClass.__Result_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Result __Result_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Result> es)
            {
                return new global::LightSwitchApplication.Result(es);
            }
            private static void __Result_Created(global::LightSwitchApplication.Result e)
            {
                e.Result_Created();
            }
            private static bool __Result_AllowSaveWithErrors(global::LightSwitchApplication.Result e)
            {
                bool result = false;
                e.Result_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Result.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int> ResultID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.ResultID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>> TestResult
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestResult) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime> TestDateTime
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.TestDateTime) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query> Query
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run> Run
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int ResultID { get; }
                new global::System.Nullable<double> TestResult { get; set; }
                new global::System.DateTime TestDateTime { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Query { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation Run { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "12.0.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int>.Entry
                    ResultID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int>.Entry(
                        "ResultID",
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._ResultID_Stub,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._ResultID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._ResultID_Validate,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._ResultID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._ResultID_OnValueChanged);
                private static void _ResultID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Result.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int>.Data> c, global::LightSwitchApplication.Result.DetailsClass d, object sf)
                {
                    c(d, ref d._ResultID, sf);
                }
                private static bool _ResultID_ComputeIsReadOnly(global::LightSwitchApplication.Result e)
                {
                    bool result = false;
                    e.ResultID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ResultID_Validate(global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ResultID_Validate(r);
                }
                private static int _ResultID_GetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.ImplementationEntity.ResultID;
                }
                private static void _ResultID_OnValueChanged(global::LightSwitchApplication.Result e)
                {
                    e.ResultID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>>.Entry
                    TestResult = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>>.Entry(
                        "TestResult",
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_Stub,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_ComputeIsReadOnly,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_Validate,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_GetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_SetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestResult_OnValueChanged);
                private static void _TestResult_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Result.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>>.Data> c, global::LightSwitchApplication.Result.DetailsClass d, object sf)
                {
                    c(d, ref d._TestResult, sf);
                }
                private static bool _TestResult_ComputeIsReadOnly(global::LightSwitchApplication.Result e)
                {
                    bool result = false;
                    e.TestResult_IsReadOnly(ref result);
                    return result;
                }
                private static void _TestResult_Validate(global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TestResult_Validate(r);
                }
                private static global::System.Nullable<double> _TestResult_GetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.ImplementationEntity.TestResult;
                }
                private static void _TestResult_SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d, global::System.Nullable<double> v)
                {
                    d.ImplementationEntity.TestResult = v;
                }
                private static void _TestResult_OnValueChanged(global::LightSwitchApplication.Result e)
                {
                    e.TestResult_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime>.Entry
                    TestDateTime = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime>.Entry(
                        "TestDateTime",
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_Stub,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_ComputeIsReadOnly,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_Validate,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_GetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_SetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._TestDateTime_OnValueChanged);
                private static void _TestDateTime_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Result.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime>.Data> c, global::LightSwitchApplication.Result.DetailsClass d, object sf)
                {
                    c(d, ref d._TestDateTime, sf);
                }
                private static bool _TestDateTime_ComputeIsReadOnly(global::LightSwitchApplication.Result e)
                {
                    bool result = false;
                    e.TestDateTime_IsReadOnly(ref result);
                    return result;
                }
                private static void _TestDateTime_Validate(global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.TestDateTime_Validate(r);
                }
                private static global::System.DateTime _TestDateTime_GetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.ImplementationEntity.TestDateTime;
                }
                private static void _TestDateTime_SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d, global::System.DateTime v)
                {
                    d.ImplementationEntity.TestDateTime = global::LightSwitchApplication.Result.DetailsClass.ClearDateTimeKind(v);
                }
                private static void _TestDateTime_OnValueChanged(global::LightSwitchApplication.Result e)
                {
                    e.TestDateTime_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query>.Entry
                    Query = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query>.Entry(
                        "Query",
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_Stub,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_ComputeIsReadOnly,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_Validate,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_GetCoreImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_GetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_SetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_Refresh,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Query_OnValueChanged);
                private static void _Query_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Result.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query>.Data> c, global::LightSwitchApplication.Result.DetailsClass d, object sf)
                {
                    c(d, ref d._Query, sf);
                }
                private static bool _Query_ComputeIsReadOnly(global::LightSwitchApplication.Result e)
                {
                    bool result = false;
                    e.Query_IsReadOnly(ref result);
                    return result;
                }
                private static void _Query_Validate(global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Query_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Query_GetCoreImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.ImplementationEntity.Query;
                }
                private static global::LightSwitchApplication.Query _Query_GetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Query, global::LightSwitchApplication.Query.DetailsClass>(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query, ref d._Query);
                }
                private static void _Query_SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d, global::LightSwitchApplication.Query v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query, ref d._Query, (i, ev) => i.Query = ev, v);
                }
                private static void _Query_Refresh(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Query, ref d._Query);
                }
                private static void _Query_OnValueChanged(global::LightSwitchApplication.Result e)
                {
                    e.Query_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run>.Entry
                    Run = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run>.Entry(
                        "Run",
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_Stub,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_ComputeIsReadOnly,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_Validate,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_GetCoreImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_GetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_SetImplementationValue,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_Refresh,
                        global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties._Run_OnValueChanged);
                private static void _Run_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Result.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run>.Data> c, global::LightSwitchApplication.Result.DetailsClass d, object sf)
                {
                    c(d, ref d._Run, sf);
                }
                private static bool _Run_ComputeIsReadOnly(global::LightSwitchApplication.Result e)
                {
                    bool result = false;
                    e.Run_IsReadOnly(ref result);
                    return result;
                }
                private static void _Run_Validate(global::LightSwitchApplication.Result e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Run_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _Run_GetCoreImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.ImplementationEntity.Run;
                }
                private static global::LightSwitchApplication.Run _Run_GetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.Run, global::LightSwitchApplication.Run.DetailsClass>(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run, ref d._Run);
                }
                private static void _Run_SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass d, global::LightSwitchApplication.Run v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run, ref d._Run, (i, ev) => i.Run = ev, v);
                }
                private static void _Run_Refresh(global::LightSwitchApplication.Result.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Result.DetailsClass.PropertySetProperties.Run, ref d._Run);
                }
                private static void _Run_OnValueChanged(global::LightSwitchApplication.Result e)
                {
                    e.Run_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, int>.Data _ResultID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.Nullable<double>>.Data _TestResult;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::System.DateTime>.Data _TestDateTime;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Query>.Data _Query;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Result, global::LightSwitchApplication.Result.DetailsClass, global::LightSwitchApplication.Run>.Data _Run;
            
        }
    
        #endregion
    }
    
    #endregion
}
