use okavango
go
with cte (

	Root_TABLE_NAME ,
	Root_TABLE_SCHEMA ,
	TABLE_CATALOG,
	TABLE_SCHEMA,
	TABLE_NAME,
	COLUMN_NAME,
	DATA_TYPE,
	IS_NULLABLE,
	CONSTRAINT_NAME,
	
	UNIQUE_TABLE_SCHEMA,
	UNIQUE_TABLE_NAME,
	UNIQUE_COLUMN_NAME
	, cteLEVEL
)
as

 (SELECT
 
	Root_TABLE_NAME = base.TABLE_NAME,
	Root_TABLE_SCHEMA = base.TABLE_SCHEMA,
	base.TABLE_CATALOG,
	base.TABLE_SCHEMA,
	base.TABLE_NAME,
	base.COLUMN_NAME,
	base.DATA_TYPE,
	base.IS_NULLABLE,
	ccu.CONSTRAINT_NAME,
	UniqueCol.TABLE_SCHEMA UNIQUE_TABLE_SCHEMA,
	
	UniqueCol.TABLE_NAME UNIQUE_TABLE_NAME,
	UniqueCol.COLUMN_NAME UNIQUE_COLUMN_NAME
	, 0 as cteLevel
FROM
INFORMATION_SCHEMA.COLUMNS base
inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
on base.COLUMN_NAME = CCU.COLUMN_NAME
and base.TABLE_NAME = ccu.TABLE_NAME
and base.TABLE_SCHEMA = CCU.TABLE_SCHEMA
inner join INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
	ON CCU.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA
	and ccu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE refCCU
ON refCCU.CONSTRAINT_SCHEMA = rc.UNIQUE_CONSTRAINT_SCHEMA
	and refCCU.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME
inner join INFORMATION_SCHEMA.COLUMNS UniqueCol
	on UniqueCol.COLUMN_NAME = refCCU.COLUMN_NAME
	and UniqueCol.TABLE_NAME = refCCU.TABLE_NAME
	and UniqueCol.TABLE_SCHEMA = refCCU.TABLE_SCHEMA

	--where  base.TABLE_NAME in ('FactActivityDetail')

UNION ALL

SELECT

	Root_TABLE_NAME = cte.Root_TABLE_NAME,
	Root_TABLE_SCHEMA = cte.Root_TABLE_SCHEMA,
	base.TABLE_CATALOG,
	base.TABLE_SCHEMA,
	base.TABLE_NAME,
	base.COLUMN_NAME,
	base.DATA_TYPE,
	base.IS_NULLABLE,
	ccu.CONSTRAINT_NAME,
	UniqueCol.TABLE_SCHEMA UNIQUE_TABLE_SCHEMA,
	UniqueCol.TABLE_NAME UNIQUE_TABLE_NAME,
	UniqueCol.COLUMN_NAME UNIQUE_COLUMN_NAME
	,
		cte.cteLEVEL + 1 AS cteLEVEL
FROM
INFORMATION_SCHEMA.COLUMNS base
inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
on base.COLUMN_NAME = CCU.COLUMN_NAME
and base.TABLE_NAME = ccu.TABLE_NAME
and base.TABLE_SCHEMA = CCU.TABLE_SCHEMA
inner join INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS RC
	ON CCU.CONSTRAINT_SCHEMA = rc.CONSTRAINT_SCHEMA
	and ccu.CONSTRAINT_NAME = rc.CONSTRAINT_NAME
inner join INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE refCCU
ON refCCU.CONSTRAINT_SCHEMA = rc.UNIQUE_CONSTRAINT_SCHEMA
	and refCCU.CONSTRAINT_NAME = rc.UNIQUE_CONSTRAINT_NAME
inner join INFORMATION_SCHEMA.COLUMNS UniqueCol
	on UniqueCol.COLUMN_NAME = refCCU.COLUMN_NAME
	and UniqueCol.TABLE_NAME = refCCU.TABLE_NAME
	and UniqueCol.TABLE_SCHEMA = refCCU.TABLE_SCHEMA

	inner join cte
	on cte.UNIQUE_TABLE_SCHEMA = base.TABLE_SCHEMA
		and cte.UNIQUE_TABLE_NAME = base.TABLE_NAME
		and NOT cte.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
		
	--where not base.TABLE_NAME in ('FactUnitConversion')
	)
	select * 
	INTO #Nodes
	from cte
	--where Root_TABLE_NAME like 'factactivityd%'

	select  
	Root_TABLE_SCHEMA,
	Root_TABLE_NAME,
	TABLE_CATALOG,
	TABLE_SCHEMA ,
	TABLE_NAME,
	cteLEVEL
	 from #Nodes
	union 
	select --#Nodes.Root_Table_Name
	N.Root_TABLE_SCHEMA,
	N.Root_TABLE_NAME,
	TABLE_CATALOG,
	UNIQUE_TABLE_SCHEMA,
	UNIQUE_TABLE_NAME, 
	cteLevel
	FROM #Nodes N
	
	/*INNER JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE CCU
	ON N.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME
	*/
	order by Root_TABLE_SCHEMA, Root_TABLE_NAME, TABLE_SCHEMA, TABLE_NAME
	
	drop table #nodes
