CREATE TABLE [dbo].[PACKAGELOG] (
    [LOGID]             INT              IDENTITY (1, 1) NOT NULL,
    [EXECUTIONID]       UNIQUEIDENTIFIER NULL,
    [PACKAGENAME]       NVARCHAR (255)   NULL,
    [PACKAGEID]         VARCHAR (50)     NULL,
    [USERNAME]          NVARCHAR (100)   NULL,
    [MACHINENAME]       NVARCHAR (255)   NULL,
    [STARTDATETIME]     DATETIME         NULL,
    [ENDDATETIME]       DATETIME         NULL,
    [SOURCENAME]        VARCHAR (255)    NULL,
    [MESSAGE]           NVARCHAR (MAX)   NULL,
    [MESSAGECODE]       INT              NULL,
    [LOGDATETIME]       DATETIME         NULL,
    [INTERACTIVEMODE]   BIT              NULL,
    [SOURCEDESCRIPTION] VARCHAR (255)    NULL,
    [TASKNAME]          VARCHAR (255)    NULL,
    [TASKID]            NVARCHAR (255)   NULL,
    [EXECSTATUS]        BIT              CONSTRAINT [DF_PACKAGELOG_EXECSTATUS] DEFAULT ((0)) NULL,
    [SERVERNAME]        NVARCHAR (255)   NULL,
    CONSTRAINT [PK__PACKAGEL__5E5499A820C44329] PRIMARY KEY CLUSTERED ([LOGID] ASC)
);

