//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PW.CustomCodeConverter.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".\\sql2012tabular")]
        public string txtExServer_Text {
            get {
                return ((string)(this["txtExServer_Text"]));
            }
            set {
                this["txtExServer_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meerkat")]
        public string txExDB_Text {
            get {
                return ((string)(this["txExDB_Text"]));
            }
            set {
                this["txExDB_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\temp\\Empty.xlsx")]
        public string txExTemplate_Text {
            get {
                return ((string)(this["txExTemplate_Text"]));
            }
            set {
                this["txExTemplate_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GitHub\\Meerkat\\Excel\\Status.xlsx")]
        public string txtExDest_Text {
            get {
                return ((string)(this["txtExDest_Text"]));
            }
            set {
                this["txtExDest_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Backups\\Subset.abf")]
        public string txtExBackupPath_Text {
            get {
                return ((string)(this["txtExBackupPath_Text"]));
            }
            set {
                this["txtExBackupPath_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\Backups\\Subset.abf")]
        public string txtExInsertPath_Text {
            get {
                return ((string)(this["txtExInsertPath_Text"]));
            }
            set {
                this["txtExInsertPath_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DimDate")]
        public string txtExDim_Text {
            get {
                return ((string)(this["txtExDim_Text"]));
            }
            set {
                this["txtExDim_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20130101")]
        public string txtexDimValue_Text {
            get {
                return ((string)(this["txtexDimValue_Text"]));
            }
            set {
                this["txtexDimValue_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkExInlMeasures_Checked {
            get {
                return ((bool)(this["chkExInlMeasures_Checked"]));
            }
            set {
                this["chkExInlMeasures_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=Meerkat;Integrated Security=True")]
        public string txtSrcConn_Text {
            get {
                return ((string)(this["txtSrcConn_Text"]));
            }
            set {
                this["txtSrcConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Left")]
        public global::System.Windows.Forms.HorizontalAlignment txtDestConn_Text {
            get {
                return ((global::System.Windows.Forms.HorizontalAlignment)(this["txtDestConn_Text"]));
            }
            set {
                this["txtDestConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLAP_GEN")]
        public string txtSchema_Text {
            get {
                return ((string)(this["txtSchema_Text"]));
            }
            set {
                this["txtSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkSchema_Checked {
            get {
                return ((bool)(this["chkSchema_Checked"]));
            }
            set {
                this["chkSchema_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'RBM\'")]
        public string txtFactPrefix_Text {
            get {
                return ((string)(this["txtFactPrefix_Text"]));
            }
            set {
                this["txtFactPrefix_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtDimPrefix_Text {
            get {
                return ((string)(this["txtDimPrefix_Text"]));
            }
            set {
                this["txtDimPrefix_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'sys_ModifiedOn\', \'sys_ModifiedBy\', \'sys_CreatedOn\', \'sys_CreatedBy\', \'Active\', \'" +
            "DeltaHash\', \'SourceKeyHash\', \'DataVersion_ID\'")]
        public string txtFieldExcl_Text {
            get {
                return ((string)(this["txtFieldExcl_Text"]));
            }
            set {
                this["txtFieldExcl_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'ActiveType\', \'DataVersion\'")]
        public string txtTableExcl_Text {
            get {
                return ((string)(this["txtTableExcl_Text"]));
            }
            set {
                this["txtTableExcl_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtFactFilter_Text {
            get {
                return ((string)(this["txtFactFilter_Text"]));
            }
            set {
                this["txtFactFilter_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtDimFilter_Text {
            get {
                return ((string)(this["txtDimFilter_Text"]));
            }
            set {
                this["txtDimFilter_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=Meerkat;Integrated Security=True\r\n")]
        public string txtStgSrcConn_Text {
            get {
                return ((string)(this["txtStgSrcConn_Text"]));
            }
            set {
                this["txtStgSrcConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MeerkatStaging")]
        public string txtStgDB_Text {
            get {
                return ((string)(this["txtStgDB_Text"]));
            }
            set {
                this["txtStgDB_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staging")]
        public string txtStgSchema_Text {
            get {
                return ((string)(this["txtStgSchema_Text"]));
            }
            set {
                this["txtStgSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fact")]
        public string txtStgFactPrefix_Text {
            get {
                return ((string)(this["txtStgFactPrefix_Text"]));
            }
            set {
                this["txtStgFactPrefix_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Dim")]
        public string txtStgDimPrefix_Text {
            get {
                return ((string)(this["txtStgDimPrefix_Text"]));
            }
            set {
                this["txtStgDimPrefix_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'sys_ModifiedOn\', \'sys_ModifiedBy\', \'sys_CreatedOn\', \'sys_CreatedBy\', \'sys_Active" +
            "\', \'Active\'")]
        public string txtStgFieldExcl_Text {
            get {
                return ((string)(this["txtStgFieldExcl_Text"]));
            }
            set {
                this["txtStgFieldExcl_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkStageDrop_Checked {
            get {
                return ((bool)(this["chkStageDrop_Checked"]));
            }
            set {
                this["chkStageDrop_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'DimDate\', \'Age\', \'templateMenueGroup\', \'DimMunicipalityGEOM\', \'ActiveType\',\'sysd" +
            "iagrams\', \'__RefactorLog\', \'GlobalSettings\'")]
        public string txtTableExclStg_Checked {
            get {
                return ((string)(this["txtTableExclStg_Checked"]));
            }
            set {
                this["txtTableExclStg_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'forms\'")]
        public string txtSchemaExclStg_Text {
            get {
                return ((string)(this["txtSchemaExclStg_Text"]));
            }
            set {
                this["txtSchemaExclStg_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("BusinessKey")]
        public string txtSrcKeyName_Text {
            get {
                return ((string)(this["txtSrcKeyName_Text"]));
            }
            set {
                this["txtSrcKeyName_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkInclKeysStg_Checked {
            get {
                return ((bool)(this["chkInclKeysStg_Checked"]));
            }
            set {
                this["chkInclKeysStg_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool chkInclRefKeysStg_Checked {
            get {
                return ((bool)(this["chkInclRefKeysStg_Checked"]));
            }
            set {
                this["chkInclRefKeysStg_Checked"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=Meerkat;Integrated Security=True")]
        public string txtTblSrcConn_Text {
            get {
                return ((string)(this["txtTblSrcConn_Text"]));
            }
            set {
                this["txtTblSrcConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=SQLNCLI11.1;Data Source=.\\sql2012;Integrated Security=SSPI;Initial Catal" +
            "og=Meerkat")]
        public string txtTblDSConn_Text {
            get {
                return ((string)(this["txtTblDSConn_Text"]));
            }
            set {
                this["txtTblDSConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=MSOLAP.4;Integrated Security=SSPI;Persist Security Info=True;Data Source" +
            "=.\\sql2012Tabular;Initial Catalog=Test")]
        public string txtTblDestConn_Text {
            get {
                return ((string)(this["txtTblDestConn_Text"]));
            }
            set {
                this["txtTblDestConn_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OLAP_Gen")]
        public string txtTblSchema_Text {
            get {
                return ((string)(this["txtTblSchema_Text"]));
            }
            set {
                this["txtTblSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtTblConnSecurity_Text {
            get {
                return ((string)(this["txtTblConnSecurity_Text"]));
            }
            set {
                this["txtTblConnSecurity_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ImpersonateServiceAccount")]
        public string txtTblImpersonationMode_Text {
            get {
                return ((string)(this["txtTblImpersonationMode_Text"]));
            }
            set {
                this["txtTblImpersonationMode_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtTblUsername_Text {
            get {
                return ((string)(this["txtTblUsername_Text"]));
            }
            set {
                this["txtTblUsername_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtTblPwd_Text {
            get {
                return ((string)(this["txtTblPwd_Text"]));
            }
            set {
                this["txtTblPwd_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Meerkat")]
        public string txtTblCubeDB_Text {
            get {
                return ((string)(this["txtTblCubeDB_Text"]));
            }
            set {
                this["txtTblCubeDB_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string txtTblImpersonationSecurity_Text {
            get {
                return ((string)(this["txtTblImpersonationSecurity_Text"]));
            }
            set {
                this["txtTblImpersonationSecurity_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=Meerkat;Integrated Security=True")]
        public string txtErrorSrc_Text {
            get {
                return ((string)(this["txtErrorSrc_Text"]));
            }
            set {
                this["txtErrorSrc_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\sql2012;Initial Catalog=MeerkatStaging;Integrated Security=True")]
        public string txtErrorStg_Text {
            get {
                return ((string)(this["txtErrorStg_Text"]));
            }
            set {
                this["txtErrorStg_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Staging")]
        public string txtErrorStagingSchema_Text {
            get {
                return ((string)(this["txtErrorStagingSchema_Text"]));
            }
            set {
                this["txtErrorStagingSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MeerkatErrors")]
        public string txtErrorDB_Text {
            get {
                return ((string)(this["txtErrorDB_Text"]));
            }
            set {
                this["txtErrorDB_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Errors")]
        public string txtErrorsSchema_Text {
            get {
                return ((string)(this["txtErrorsSchema_Text"]));
            }
            set {
                this["txtErrorsSchema_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\'sys_ModifiedOn\', \'sys_ModifiedBy\', \'sys_CreatedOn\', \'sys_CreatedBy\', \'sys_Active" +
            "\', \'Active\'")]
        public string txtErrorsFieldExcl_Text {
            get {
                return ((string)(this["txtErrorsFieldExcl_Text"]));
            }
            set {
                this["txtErrorsFieldExcl_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool chkErrorsDropDB_Checked {
            get {
                return ((bool)(this["chkErrorsDropDB_Checked"]));
            }
            set {
                this["chkErrorsDropDB_Checked"] = value;
            }
        }
    }
}
